# Generated by Django 5.2.8 on 2026-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='disease_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
